name: awesome-haskell-videos
version: 0.1.0
license: BSD3
synopsis: Generate awesome haskell videos list
description: See README at <https://github.com/andys8/awesome-haskell-videos#readme>
maintainer: andys8@users.noreply.github.com
github: andys8/awesome-haskell-videos
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - http-conduit

executable:
  main: generate.hs
